version: "3.3"
services:
  samplefolder:
    build:
      context: ./nextjs-jest
      dockerfile: Dockerfile
    image: nodejsimg
    container_name: nodejscont
    ports:
      - "3000:3000"
    restart: on-failure
